In [3]:
#Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.
import numpy as np

followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Followers Array:", followers)
print("Shape:", followers.shape)
print("Dimensions:", followers.ndim)
print("Data Type:", followers.dtype)

Followers Array: [   1200   15000   67000  340000 1250000]
Shape: (5,)
Dimensions: 1
Data Type: int64


In [4]:
#Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.

order_ids = np.arange(101, 111)

print("Order IDs:", order_ids)
print("Size:", order_ids.size)

Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10


In [ ]:
#Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment


like_matrix = np.eye(3)

print("Identity Matrix:")
print(like_matrix)

# The diagonal values are 1 because they represent
# while all other values are 0.

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>
import numpy as np

scores = [45, 67, 120, 89, 54]

score_array = np.array(scores)

print("Score Array:", score_array)
print("Bytes per element:", score_array.itemsize)

Score Array: [ 45  67 120  89  54]
Bytes per element: 8
