In [1]:
import numpy as np
#Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.

friend1_steps = np.array([5000, 7000, 8000, 6500, 9000, 7500, 6800])


friend2_steps = np.array([4800, 7200, 7900, 6400, 8800, 7600, 6900])

total_steps = friend1_steps + friend2_steps

step_difference = friend1_steps - friend2_steps

step_product = friend1_steps * friend2_steps

step_ratio = friend1_steps / friend2_steps

print("Total steps each day:", total_steps)
print("Difference in steps each day:", step_difference)
print("Product of steps each day:", step_product)
print("Step ratio (Friend1 / Friend2) each day:", step_ratio)


Total steps each day: [ 9800 14200 15900 12900 17800 15100 13700]
Difference in steps each day: [ 200 -200  100  100  200 -100 -100]
Product of steps each day: [24000000 50400000 63200000 41600000 79200000 57000000 46920000]
Step ratio (Friend1 / Friend2) each day: [1.04166667 0.97222222 1.01265823 1.015625   1.02272727 0.98684211
 0.98550725]


In [ ]:
#Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.


user_preferences = np.array([
    [0.8, 0.1, 0.4],
    [0.3, 0.7, 0.5],
    [0.6, 0.3, 0.9]
])

song_popularity = np.array([
    [0.9, 0.4, 0.7],
    [0.6, 0.8, 0.3],
    [0.5, 0.9, 0.6]
])

# Using dot()
recommendations_dot = np.dot(user_preferences, song_popularity)

# Using matmul()
recommendations_matmul = user_preferences @ song_popularity

print("Recommendations using dot():")
print(recommendations_dot)

print("\nRecommendations using matmul():")
print(recommendations_matmul)


Recommendations using dot():
[[0.98 0.76 0.83]
 [0.94 1.13 0.72]
 [1.17 1.29 1.05]]

Recommendations using matmul():
[[0.98 0.76 0.83]
 [0.94 1.13 0.72]
 [1.17 1.29 1.05]]


In [3]:
#Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.


image = np.array([
    [120, 150, 180, 200],
    [100, 130, 160, 190],
    [80, 110, 140, 170],
    [60, 90, 120, 150]
])

print("Original Image:")
print(image)


rotated = image.T

print("\nTransposed Image:")
print(rotated)

print("\nMean:", np.mean(image))
print("Median:", np.median(image))
print("Standard Deviation:", np.std(image))
print("Variance:", np.var(image))

Original Image:
[[120 150 180 200]
 [100 130 160 190]
 [ 80 110 140 170]
 [ 60  90 120 150]]

Transposed Image:
[[120 100  80  60]
 [150 130 110  90]
 [180 160 140 120]
 [200 190 170 150]]

Mean: 134.375
Median: 135.0
Standard Deviation: 39.205986468905486
Variance: 1537.109375


In [4]:
#ake a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em

ratings = np.array([
    [4, 2, 1],
    [0, 5, 3],
    [2, 1, 4]
])

print("Original Matrix:")
print(ratings)

# Determinant
det = np.linalg.det(ratings)
print("\nDeterminant:")
print(det)

# Inverse
inv = np.linalg.inv(ratings)
print("\nInverse:")
print(inv)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Original Matrix:
[[4 2 1]
 [0 5 3]
 [2 1 4]]

Determinant:
69.99999999999996

Inverse:
[[ 0.24285714 -0.1         0.01428571]
 [ 0.08571429  0.2        -0.17142857]
 [-0.14285714  0.          0.28571429]]

Eigenvalues:
[2.81647627+1.25269018j 2.81647627-1.25269018j 7.36704746+0.j        ]

Eigenvectors:
[[ 0.21777685+0.46275206j  0.21777685-0.46275206j -0.54515586+0.j        ]
 [-0.658274  +0.j         -0.658274  -0.j         -0.658141  +0.j        ]
 [ 0.47911896-0.27487113j  0.47911896+0.27487113j -0.51928366+0.j        ]]


In [6]:
#Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

orders = np.array([
    [120, 135, 150, 160, 145, 170],
    [110, 125, 140, 155, 165, 180]
])

print("Original Array:")
print(orders)

# Reshape to (3,4)
reshaped = orders.reshape(3, 4)
print("Reshaped Array (3x4):")
print(reshaped)

# Flatten the array
flattened = reshaped.flatten()
print("\nFlattened Array:")
print(flattened)

# Split into two equal parts
split_arrays = np.split(flattened, 2)
print("\nSplit Arrays:")
print(split_arrays)

stacked = np.vstack(split_arrays)
print("\nVertically Stacked Array:")
print(stacked)

Original Array:
[[120 135 150 160 145 170]
 [110 125 140 155 165 180]]
Reshaped Array (3x4):
[[120 135 150 160]
 [145 170 110 125]
 [140 155 165 180]]

Flattened Array:
[120 135 150 160 145 170 110 125 140 155 165 180]

Split Arrays:
[array([120, 135, 150, 160, 145, 170]), array([110, 125, 140, 155, 165, 180])]

Vertically Stacked Array:
[[120 135 150 160 145 170]
 [110 125 140 155 165 180]]
