In [1]:
#Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only. 2.
import numpy as np

ratings = np.array([
    [5, 4, 3, 5, 4],
    [4, 5, 4, 3, 5],
    [3, 4, 5, 4, 5],
    [5, 5, 4, 4, 3]
])

print("Ratings Matrix:")
print(ratings)

print("Ratings of 2nd and 3rd Users:")
print(ratings[1:3])

Ratings Matrix:
[[5 4 3 5 4]
 [4 5 4 3 5]
 [3 4 5 4 5]
 [5 5 4 4 3]]
Ratings of 2nd and 3rd Users:
[[4 5 4 3 5]
 [3 4 5 4 5]]


In [2]:
#Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em


steps = np.array([7500, 8200, 9000, 6800, 10000, 7900, 8500, 9200, 7600, 8800])

print("Daily Steps:")
print(steps)

print("Steps greater than 8000:")
print(steps[steps > 8000])

Daily Steps:
[ 7500  8200  9000  6800 10000  7900  8500  9200  7600  8800]
Steps greater than 8000:
[ 8200  9000 10000  8500  9200  8800]


In [4]:
#Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.

scores = np.array([180, 195, 210, 175, 220, 198, 205, 190])

print("IPL Scores:")
print(scores)

print("Scores from Matches 2, 5, and 7:")
print(scores[[1, 4, 6]])

IPL Scores:
[180 195 210 175 220 198 205 190]
Scores from Matches 2, 5, and 7:
[195 220 205]


In [ ]:
#Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.

prices = np.array([499, 999, 1499, 799, 299])

discounted_prices = prices * 0.90

print("Original Prices:")
print(prices)

print("Prices after 10% Discount:")
print(discounted_prices)

In [6]:
#Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged

ratings = np.array([5, -2, 3, 0, -1, 4, -5, 2])

print(ratings[ratings >= 0])


[5 3 0 4 2]
